### ISSUE TITLE
Slash command menu not recolored

### ISSUE THREAD

**Issue by asorel1942** [rmkx/rmkx.github.io#1]
The slash command menu is the same color as it is on the default Discord theme, rather than matching the rest of the theme:
![image](https://user-images.githubusercontent.com/33983895/114326248-eee21a80-9b01-11eb-8339-3c8f0b7c2f95.png)

**Comment by rmkx** [comment]
Thank you for the heads up, I completely forgot about that panel. It should be fixed now.

**Comment by asorel1942** [comment]
Since this is effectively the same issue, figured I'd just reopen this:
The `Alt+/` menu is also not colored by the theme, and only has default colors.

**Comment by rmkx** [comment]
Thank you again for the report. A fix has been pushed, it should be styled as soon as your discord updates its cache.
