### ISSUE TITLE
Issue with BetterRoleColors

### ISSUE THREAD

**Issue by ShadowVappy** [rmkx/rmkx.github.io#9]
BetterRoleColors plugin does not use the role colour correctly for mentions with this theme. It still works correctly for mentions within replies, but not for general replies.

**Comment by rmkx** [comment]
Not sure which of the themes you're referring to, but in the plugin settings there's one under Global settings that should make it work

**Comment by ShadowVappy** [comment]
Sorry, I'm referring to Duality theme. I have the !important setting enabled in the plugin global settings and the mentions still are not coloured by the plugin.

**Comment by rmkx** [comment]
Does it work for you when not using a theme? Because I've tried without a theme and seems like the problem is the plugin, not the theme.

**Comment by ShadowVappy** [comment]
Yeah, without a theme the mentions are working the same as in the Duality theme. I'm sorry, I based my assumptions on the plugin working on other themes I had used, as I had not tried the plugin without a theme.
